language: elixir
elixir:
  - 1.7
  - 1.8
otp_release:
  - 20.3
  - 21.3
env:
  - STRICT=true
  - STRICT=false
matrix:
  exclude:
    - otp_release: 20.3
      env: STRICT=true
    - otp_release: 21.3
      env: STRICT=false
notifications:
  email:
    - mitch@rokkincat.com
script:
  - if [ "$STRICT" = "true" ]; then mix compile --warnings-as-errors; fi
  - mix test
  - if [ "$STRICT" = "true" ]; then travis_wait mix dialyzer; fi
  - if [ "$STRICT" = "true" ]; then mix format --dry-run --check-formatted; fi
cache:
  directories:
    - .mix
    - _build
