language: elixir
elixir:
  - 1.10
otp_release:
  - 21.3
  - 22.3
  - 23.0
env:
  - STRICT=true
  - STRICT=false
matrix:
  exclude:
    - elixir: 1.10
      env: STRICT=false
notifications:
  email:
    - mitch@rokkincat.com
script:
  - if [ "$STRICT" = "true" ]; then mix compile --warnings-as-errors; fi
  - mix test
  - if [ "$STRICT" = "true" ]; then travis_wait mix dialyzer; fi
  - if [ "$STRICT" = "true" ]; then mix format --dry-run --check-formatted; fi
cache:
  directories:
    - .mix
    - _build
    - priv/plts
