language: elixir
elixir:
  - 1.7
  - 1.8
  - 1.9
  - 1.10
otp_release:
  - 20.3
  - 21.3
  - 22.1
env:
  - STRICT=true
  - STRICT=false
matrix:
  exclude:
    - elixir: 1.7
      env: STRICT=true
    - elixir: 1.8
      env: STRICT=true
    - elixir: 1.9
      env: STRICT=true
    - elixir: 1.10
      env: STRICT=false
    - elixir: 1.10
      otp_release: 20.3
notifications:
  email:
    - mitch@rokkincat.com
script:
  - if [ "$STRICT" = "true" ]; then mix compile --warnings-as-errors; fi
  - mix test
  - if [ "$STRICT" = "true" ]; then travis_wait mix dialyzer; fi
  - if [ "$STRICT" = "true" ]; then mix format --dry-run --check-formatted; fi
cache:
  directories:
    - .mix
    - _build
