language: elixir
elixir:
  - 1.3.4
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 18.3
  - 19.3
  - 20.2
env:
  - MIX_FORMAT=true
  - MIX_FORMAT=false
matrix:
  exclude:
    - elixir: 1.6
      env: MIX_FORMAT=false
    - elixir: 1.3.4
      env: MIX_FORMAT=true
    - elixir: 1.4
      env: MIX_FORMAT=true
    - elixir: 1.5
      env: MIX_FORMAT=true
    - elixir: 1.6
      otp_release: 18.3
    - elixir: 1.3.4
      otp_release: 20.2
notifications:
  email:
    - mitch@rokkincat.com
script:
  - mix test
  - mix credo
  - mix dialyzer
  - if [ "$MIX_FORMAT" = "true" ]; then mix format --dry-run --check-formatted; fi
cache:
  directories:
    - .mix
    - _build
